# Generated by scripts/gen-brew-formula.sh — do not edit by hand.
class Harness < Formula
  desc "Deterministic agentic engineering harness with policy gates, sensors, MCPs, hooks, sandboxed runs, and portable backups"
  homepage "https://github.com/rodolfopeixoto/harnessx"
  version "0.103.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.103.0/harness-darwin-arm64.tar.gz"
      sha256 "5020b22399f95b28abb7c243184a38848ce2bf234e4175b72333d1fbb235c0a2"
    end
    on_intel do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.103.0/harness-darwin-amd64.tar.gz"
      sha256 "7af172524d88d990b410dba2b2b12bb8e6241925e293862024cb55cb7748301a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.103.0/harness-linux-arm64.tar.gz"
      sha256 "61f81a0a4cf0bdb62ba498fdca47a5afc3edc7749d96039f900b72a189e2b3d5"
    end
    on_intel do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.103.0/harness-linux-amd64.tar.gz"
      sha256 "47460b465eb5bb4122aee16fa391b1fae3791d1fa82d4e6d3949b5a739a56f22"
    end
  end

  def install
    bin_name = "harness-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch == :arm64 ? "arm64" : "amd64"}"
    bin.install bin_name => "harness"
  end

  test do
    assert_match "harness v", shell_output("#{bin}/harness version")
  end
end
