# Generated by scripts/gen-brew-formula.sh — do not edit by hand.
class Harnessx < Formula
  desc "Deterministic agentic engineering harness with policy gates, sensors, MCPs, hooks, sandboxed runs, and portable backups"
  homepage "https://github.com/rodolfopeixoto/harnessx"
  version "0.25.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.25.0/harness-darwin-arm64.tar.gz"
      sha256 "56ef55eb8ccf29e31f48cd2c5eead26d5aaa5b754ec26a31c8de01981331ca7d"
    end
    on_intel do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.25.0/harness-darwin-amd64.tar.gz"
      sha256 "c214b4105e6de201826ea8b1380c0f9146217370176e691f0b6c08192d6a8928"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.25.0/harness-linux-arm64.tar.gz"
      sha256 "4541b4cdd3b6f6ec5d9a4a061732b2782e811ae0c5275a6b04b1380d495bf465"
    end
    on_intel do
      url "https://github.com/rodolfopeixoto/harnessx/releases/download/v0.25.0/harness-linux-amd64.tar.gz"
      sha256 "9b6b977485c96c0c1195834b6c9e1d8329a423fa53360eab15040c13321d5e4a"
    end
  end

  def install
    bin_name = "harness-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch == :arm64 ? "arm64" : "amd64"}"
    bin.install bin_name => "harness"
  end

  test do
    assert_match "harness v", shell_output("#{bin}/harness version")
  end
end
