source 'https://rubygems.org'

ruby '>= 3.2'

gem 'rails', '~> 7.1'
gem 'puma', '~> 6.4'
gem 'bootsnap', '>= 1.18', require: false

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop-rails', '~> 2.24', require: false
end
