#!/usr/bin/env bash
# Emits a Homebrew formula for HarnessX pointed at a release tag.
# Assumes `dist/harness-{darwin,linux}-{amd64,arm64}.tar.gz.sha256`
# already exist (i.e. run `make release` first).
#
# Usage:
#   scripts/gen-brew-formula.sh v0.15.0 > Formula/harness.rb
#   scripts/gen-brew-formula.sh v0.15.0 rodolfopeixoto/harnessx > Formula/harness.rb
#
# Drop the generated file into the rodolfopeixoto/homebrew-tap repo and
# users get:
#   brew tap rodolfopeixoto/tap
#   brew install harness

set -euo pipefail

tag="${1:?usage: $0 <vX.Y.Z> [repo]}"
repo="${2:-rodolfopeixoto/harnessx}"

sha() {
  local platform="$1"
  local sum_file="dist/harness-${platform}.tar.gz.sha256"
  if [[ ! -f "$sum_file" ]]; then
    echo "missing $sum_file (run: make release)" >&2
    exit 1
  fi
  awk '{print $1}' "$sum_file"
}

cat <<RUBY
# Generated by scripts/gen-brew-formula.sh — do not edit by hand.
class Harness < Formula
  desc "Deterministic agentic engineering harness with policy gates, sensors, MCPs, hooks, sandboxed runs, and portable backups"
  homepage "https://github.com/${repo}"
  version "${tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${repo}/releases/download/${tag}/harness-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "https://github.com/${repo}/releases/download/${tag}/harness-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${repo}/releases/download/${tag}/harness-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "https://github.com/${repo}/releases/download/${tag}/harness-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin_name = "harness-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch == :arm64 ? "arm64" : "amd64"}"
    bin.install bin_name => "harness"
  end

  test do
    assert_match "harness v", shell_output("#{bin}/harness version")
  end
end
RUBY
