# Third-Party Licenses

This file is regenerated by `make licenses`. Do not edit by hand.

HarnessX itself is MIT (see `LICENSE`). The following Go modules are
linked into the `harness` binary; each carries its own license.

| Module | License | URL |
|---|---|---|
{{range .}}| `{{.Name}}` | {{.LicenseName}} | {{.LicenseURL}} |
{{end}}
