// SPDX-License-Identifier: MIT

package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ropeixoto/harnessx/internal/app/agentcmd"
	mcppkg "github.com/ropeixoto/harnessx/internal/mcppkg"
	"github.com/ropeixoto/harnessx/internal/ui"
	"github.com/ropeixoto/harnessx/internal/version"
)

func newOnboardingCmd() *cobra.Command {
	var interactive bool
	c := &cobra.Command{
		Use:   "onboarding",
		Short: "Detect installed agent CLIs + dev tools and print next-step recipe",
		RunE: func(cmd *cobra.Command, _ []string) error {
			dir, err := cwd()
			if err != nil {
				return err
			}
			if interactive {
				return runOnboardingInteractive(cmd.Context(), cmd.InOrStdin(), cmd.OutOrStdout(), dir)
			}
			return runOnboarding(cmd.Context(), cmd.OutOrStdout(), dir)
		},
	}
	c.Flags().BoolVar(&interactive, "interactive", false, "prompt to pin a suggested adapter and run setup actions")
	return c
}

func runOnboardingInteractive(ctx context.Context, in io.Reader, out io.Writer, root string) error {
	r := gatherOnboarding(ctx, root)
	renderOnboarding(out, r)
	reader := bufio.NewReader(in)

	offerMissingToolInstalls(ctx, reader, out, r.Tools)
	if pinErr := offerAdapterPin(ctx, reader, out, root, r.Adapters); pinErr != nil {
		return pinErr
	}
	offerMultiAdapterRoutes(reader, out, root, r.Adapters)
	offerBackupQuickstart(ctx, reader, out, root)
	offerScaffold(ctx, reader, out)
	offerCiInstallMissing(ctx, reader, out, root)
	offerMCPSetup(ctx, reader, out, root)
	offerDockerSetup(reader, out, root)
	fmt.Fprintln(out, "\n"+ui.Heading.Render("setup done")+" — open a chat with "+ui.Accent.Render("harness chat --auto-gate"))
	return nil
}

func installedAdapterIDs(adapters []checkedTool) []string {
	out := make([]string, 0, len(adapters))
	for _, a := range adapters {
		if a.found {
			out = append(out, a.name)
		}
	}
	return out
}

func offerMultiAdapterRoutes(in *bufio.Reader, out io.Writer, root string, adapters []checkedTool) {
	installed := installedAdapterIDs(adapters)
	if len(installed) < 2 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("multi-adapter routing"))
	fmt.Fprintln(out, "  map task tags (planning / implementation / cheap_review) to different adapters")
	fmt.Fprintln(out, "  so /plan hits a cheap model and plain text hits a stronger one.")
	if !askYesNo(in, out, "configure routes now?", true) {
		fmt.Fprintln(out, "  skipped — edit .harness/config/routes.yaml later")
		return
	}
	tasks := []string{"planning", "implementation", "cheap_review"}
	picks := map[string]string{}
	for _, tag := range tasks {
		idx, err := askChoice(in, out, "  "+ui.Accent.Render(tag)+" — pick adapter:", installed, 0)
		if err != nil {
			return
		}
		picks[tag] = installed[idx]
	}
	dir := filepath.Join(root, ".harness", "config")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintf(out, "  %s mkdir: %v\n", ui.MarkFail(), err)
		return
	}
	body := renderRoutesYAML(picks, installed)
	path := filepath.Join(dir, "routes.yaml")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fmt.Fprintf(out, "  %s write %s: %v\n", ui.MarkFail(), path, err)
		return
	}
	fmt.Fprintf(out, "  %s wrote %s\n", ui.MarkSuccess(), ui.Accent.Render(path))
}

func renderRoutesYAML(picks map[string]string, installed []string) string {
	tasks := []string{"planning", "implementation", "cheap_review"}
	var b strings.Builder
	b.WriteString("# generated by `harness onboarding --interactive`\n")
	b.WriteString("routes:\n")
	for _, tag := range tasks {
		primary, ok := picks[tag]
		if !ok {
			continue
		}
		b.WriteString("  " + tag + ":\n")
		b.WriteString("    primary: " + primary + "\n")
		fallback := []string{}
		for _, id := range installed {
			if id != primary {
				fallback = append(fallback, id)
			}
		}
		if len(fallback) > 0 {
			b.WriteString("    fallback: [" + strings.Join(fallback, ", ") + "]\n")
		}
	}
	return b.String()
}

func offerBackupQuickstart(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	if _, err := exec.LookPath("rclone"); err != nil {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("backup quickstart"))
	fmt.Fprintln(out, "  print the 3-step recipe to configure a remote (gdrive / s3 / fs)")
	if !askYesNo(in, out, "show recipe?", false) {
		fmt.Fprintln(out, "  skipped — run `harness backup quickstart` later")
		return
	}
	if err := runHarnessSubcommand(ctx, out, root, "backup", "quickstart"); err != nil {
		fmt.Fprintf(out, "  %s backup quickstart: %v\n", ui.MarkFail(), err)
	}
}

func offerCiInstallMissing(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	if _, err := exec.LookPath("pip"); err != nil {
		if _, err2 := exec.LookPath("pip3"); err2 != nil {
			return
		}
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("python sensor tools"))
	fmt.Fprintln(out, "  pip-install optional bandit / mypy / pip-audit so `harness ci` runs the full sensor catalogue")
	if !askYesNo(in, out, "install now?", false) {
		fmt.Fprintln(out, "  skipped — run `harness ci --install-missing` later")
		return
	}
	if err := runHarnessSubcommand(ctx, out, root, "ci", "--install-missing"); err != nil {
		fmt.Fprintf(out, "  %s ci --install-missing: %v\n", ui.MarkFail(), err)
	}
}

func offerMissingToolInstalls(ctx context.Context, in *bufio.Reader, out io.Writer, tools []checkedTool) {
	missing := []checkedTool{}
	for _, t := range tools {
		if !t.found && strings.HasPrefix(t.installHint, "brew install ") {
			missing = append(missing, t)
		}
	}
	if len(missing) == 0 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("missing system tools"))
	for _, t := range missing {
		fmt.Fprintf(out, "  %s missing — install via %s ?\n", ui.Accent.Render(t.name), ui.Muted.Render(t.installHint))
		if !askYesNo(in, out, "  install now?", true) {
			fmt.Fprintln(out, "  skipped "+t.name)
			continue
		}
		args := strings.Fields(strings.TrimPrefix(t.installHint, "brew install "))
		bargs := append([]string{"install"}, args...)
		fmt.Fprintln(out, "  → brew "+strings.Join(bargs, " "))
		c := exec.CommandContext(ctx, "brew", bargs...)
		c.Stdout = out
		c.Stderr = out
		if err := c.Run(); err != nil {
			fmt.Fprintf(out, "  %s brew install %s failed: %v\n", ui.MarkFail(), t.name, err)
			continue
		}
		fmt.Fprintln(out, "  "+ui.MarkSuccess()+" installed "+t.name)
	}
}

func offerAdapterPin(ctx context.Context, in *bufio.Reader, out io.Writer, root string, adapters []checkedTool) error {
	installed := []string{}
	for _, a := range adapters {
		if a.found {
			installed = append(installed, a.name)
		}
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("adapter pin"))
	if len(installed) == 0 {
		fmt.Fprintln(out, "  "+ui.MarkWarn()+" no agent CLI on PATH; install one of: claude / codex / gemini / kimi / ollama")
		return nil
	}
	choice, err := askChoice(in, out, "  pick the default adapter:", append(installed, "skip"), 0)
	if err != nil {
		return err
	}
	if choice == len(installed) {
		fmt.Fprintln(out, "  skipped pin — use `harness use <id>` later")
		return nil
	}
	pick := installed[choice]
	if err := runHarnessSubcommand(ctx, out, root, "use", pick); err != nil {
		return fmt.Errorf("onboarding: pin %s: %w", pick, err)
	}
	fmt.Fprintln(out, "  "+ui.MarkSuccess()+" pinned "+ui.Accent.Render(pick))
	return nil
}

func offerScaffold(ctx context.Context, in *bufio.Reader, out io.Writer) {
	fmt.Fprintln(out, "\n"+ui.Heading.Render("scaffold a starter project?"))
	stacks := []string{
		"python-ecommerce (FastAPI todo skeleton)",
		"rails (Rails 7 API skeleton)",
		"go (net/http server)",
		"rust (Axum web server)",
		"ruby (Sinatra app)",
		"react (Vite + Vitest)",
		"skip",
	}
	idx, err := askChoice(in, out, "  pick a stack:", stacks, len(stacks)-1)
	if err != nil {
		return
	}
	if idx == len(stacks)-1 {
		fmt.Fprintln(out, "  skipped scaffold — run `harness new <stack> ./dir --yes --with-deps` later")
		return
	}
	stackID := strings.Fields(stacks[idx])[0]
	target, ok := askLine(in, out, "  target directory", "./my-"+stackID)
	if !ok {
		return
	}
	withDeps := askYesNo(in, out, "  install dependencies (--with-deps)?", true)
	args := []string{"new", stackID, target, "--yes"}
	if withDeps {
		args = append(args, "--with-deps")
	}
	if err := runHarnessSubcommand(ctx, out, ".", args...); err != nil {
		fmt.Fprintf(out, "  %s scaffold failed: %v\n", ui.MarkFail(), err)
		return
	}
	fmt.Fprintf(out, "  %s scaffold ready at %s\n", ui.MarkSuccess(), ui.Accent.Render(target))
	fmt.Fprintf(out, "  next: %s\n", ui.Muted.Render("cd "+target+" && harness chat --auto-gate"))
}

func offerMCPSetup(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	names, err := mcppkg.List()
	if err != nil || len(names) == 0 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("MCP servers"))
	fmt.Fprintf(out, "  bundled templates: %s\n", strings.Join(names, ", "))
	fmt.Fprintln(out, "  external search:   harness mcp search <term>  (modelcontextprotocol registry)")
	choice, err := askChoice(in, out, "  setup:", []string{
		"install all defaults (recommended)",
		"search bundled by substring (then pick a few)",
		"skip — configure later",
	}, 0)
	if err != nil {
		return
	}
	switch choice {
	case 0:
		for _, name := range names {
			if err := runHarnessSubcommand(ctx, out, root, "mcp", "install", name, "--yes"); err != nil {
				fmt.Fprintf(out, "  %s install %s: %v\n", ui.MarkFail(), name, err)
				continue
			}
			fmt.Fprintf(out, "  %s installed %s\n", ui.MarkSuccess(), ui.Accent.Render(name))
		}
	case 1:
		offerMCPSubstringPick(ctx, in, out, root, names)
	default:
		fmt.Fprintln(out, "  skipped — run `harness mcp install <name>` later")
	}
}

func offerMCPSubstringPick(ctx context.Context, in *bufio.Reader, out io.Writer, root string, names []string) {
	for {
		fmt.Fprint(out, "  filter (substring, empty to list all, 'done' to finish): ")
		line, _ := in.ReadString('\n')
		q := strings.TrimSpace(line)
		if q == "done" {
			return
		}
		filtered := []string{}
		for _, n := range names {
			if q == "" || strings.Contains(n, q) {
				filtered = append(filtered, n)
			}
		}
		if len(filtered) == 0 {
			fmt.Fprintf(out, "  %s no matches for %q\n", ui.MarkWarn(), q)
			continue
		}
		filtered = append(filtered, "done")
		idx, err := askChoice(in, out, "  pick:", filtered, len(filtered)-1)
		if err != nil || idx == len(filtered)-1 {
			return
		}
		name := filtered[idx]
		if err := runHarnessSubcommand(ctx, out, root, "mcp", "install", name, "--yes"); err != nil {
			fmt.Fprintf(out, "  %s install %s: %v\n", ui.MarkFail(), name, err)
			continue
		}
		fmt.Fprintf(out, "  %s installed %s\n", ui.MarkSuccess(), ui.Accent.Render(name))
	}
}

func offerDockerSetup(in *bufio.Reader, out io.Writer, root string) {
	stack := detectDockerStack(root)
	if stack == "" {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("docker setup"))
	fmt.Fprintf(out, "  detected stack: %s — scaffold Dockerfile + docker-compose.yml?\n", ui.Accent.Render(stack))
	if !askYesNo(in, out, "write files?", false) {
		fmt.Fprintln(out, "  skipped")
		return
	}
	df, compose := renderDockerScaffold(stack)
	wrote := []string{}
	for _, f := range []struct {
		path string
		body string
	}{
		{filepath.Join(root, "Dockerfile"), df},
		{filepath.Join(root, "docker-compose.yml"), compose},
	} {
		if _, err := os.Stat(f.path); err == nil {
			fmt.Fprintf(out, "  %s %s already exists — skipping\n", ui.MarkWarn(), f.path)
			continue
		}
		if err := os.WriteFile(f.path, []byte(f.body), 0o644); err != nil {
			fmt.Fprintf(out, "  %s write %s: %v\n", ui.MarkFail(), f.path, err)
			continue
		}
		wrote = append(wrote, f.path)
	}
	for _, p := range wrote {
		fmt.Fprintf(out, "  %s wrote %s\n", ui.MarkSuccess(), ui.Accent.Render(p))
	}
}

func detectDockerStack(root string) string {
	probes := []struct {
		marker string
		stack  string
	}{
		{"go.mod", "go"},
		{"pyproject.toml", "python"},
		{"requirements.txt", "python"},
		{"package.json", "node"},
	}
	for _, p := range probes {
		if _, err := os.Stat(filepath.Join(root, p.marker)); err == nil {
			return p.stack
		}
	}
	return ""
}

func renderDockerScaffold(stack string) (string, string) {
	switch stack {
	case "go":
		return dockerfileGo, composeGeneric(8080)
	case "python":
		return dockerfilePython, composeGeneric(8000)
	case "node":
		return dockerfileNode, composeGeneric(3000)
	}
	return "", ""
}

const dockerfileGo = `FROM golang:1.21-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app ./...

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/app /app
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/app"]
`

const dockerfilePython = `FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -e .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
`

const dockerfileNode = `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]
`

func composeGeneric(port int) string {
	return fmt.Sprintf(`services:
  app:
    build: .
    ports:
      - "%d:%d"
    mem_limit: 2g
    memswap_limit: 2g
    cpus: '2.0'
    restart: unless-stopped
`, port, port)
}

func askYesNo(in io.Reader, out io.Writer, prompt string, defaultYes bool) bool {
	def := "Y/n"
	if !defaultYes {
		def = "y/N"
	}
	fmt.Fprintf(out, "  %s [%s]: ", prompt, def)
	answer := trimAndLower(readPromptLine(in))
	if answer == "" {
		return defaultYes
	}
	switch answer {
	case "y", "yes", "1", "true", "ok":
		return true
	case "n", "no", "0", "false":
		return false
	}
	return defaultYes
}

func askChoice(in io.Reader, out io.Writer, prompt string, options []string, defaultIdx int) (int, error) {
	if len(options) == 0 {
		return 0, fmt.Errorf("askChoice: no options")
	}
	fmt.Fprintln(out, prompt)
	for i, o := range options {
		marker := "  "
		if i == defaultIdx {
			marker = "→ "
		}
		fmt.Fprintf(out, "  %s%d) %s\n", marker, i+1, o)
	}
	fmt.Fprintf(out, "  pick [1-%d, default %d]: ", len(options), defaultIdx+1)
	answer := trimAndLower(readPromptLine(in))
	if answer == "" {
		return defaultIdx, nil
	}
	n, err := strconv.Atoi(answer)
	if err != nil || n < 1 || n > len(options) {
		fmt.Fprintf(out, "  %s invalid choice %q — using default %d\n", ui.MarkWarn(), answer, defaultIdx+1)
		return defaultIdx, nil
	}
	return n - 1, nil
}

func askLine(in io.Reader, out io.Writer, prompt, defaultVal string) (string, bool) {
	fmt.Fprintf(out, "  %s [%s]: ", prompt, defaultVal)
	answer := strings.TrimSpace(readPromptLine(in))
	if answer == "" {
		return defaultVal, true
	}
	return answer, true
}

func readPromptLine(in io.Reader) string {
	if br, ok := in.(*bufio.Reader); ok {
		line, _ := br.ReadString('\n')
		return strings.TrimRight(line, "\r\n")
	}
	buf := make([]byte, 256)
	n, _ := in.Read(buf)
	answer := ""
	for i := 0; i < n; i++ {
		if buf[i] == '\n' || buf[i] == '\r' {
			break
		}
		answer += string(buf[i])
	}
	return answer
}

func trimAndLower(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == ' ' || c == '\t' {
			continue
		}
		if c >= 'A' && c <= 'Z' {
			c += 32
		}
		out = append(out, c)
	}
	return string(out)
}

func runHarnessSubcommand(ctx context.Context, out io.Writer, dir string, args ...string) error {
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Dir = dir
	cmd.Stdout = out
	cmd.Stderr = out
	return cmd.Run()
}

type toolCheck struct {
	name        string
	binary      string
	purpose     string
	installHint string
}

var onboardingTools = []toolCheck{
	{"git", "git", "version control (required)", "brew install git"},
	{"python3", "python3", "python scaffolds + venv", "brew install python"},
	{"node", "node", "react/typescript scaffolds", "brew install node"},
	{"uv", "uv", "python dep installer (used by --with-deps)", "brew install uv"},
	{"rg", "rg", "secrets_scan + context provider", "brew install ripgrep"},
	{"jq", "jq", "tutorial curl examples", "brew install jq"},
	{"rclone", "rclone", "harness backup snapshot", "brew install rclone"},
}

var onboardingAdapters = []toolCheck{
	{"claude", "claude", "Anthropic Claude Code CLI", "https://docs.claude.com/en/docs/claude-code"},
	{"codex", "codex", "OpenAI Codex CLI", "https://github.com/openai/codex"},
	{"antigravity", "antigravity", "Google Antigravity CLI (replaces Gemini CLI)", "https://antigravity.google/download"},
	{"kimi", "kimi", "Moonshot Kimi CLI", "https://platform.moonshot.cn/"},
	{"ollama", "ollama", "Local Ollama runtime", "https://ollama.com/"},
}

type onboardingResult struct {
	Tools     []checkedTool
	Adapters  []checkedTool
	HarnessV  string
	Suggested string
}

type checkedTool struct {
	toolCheck
	found   bool
	version string
}

func runOnboarding(ctx context.Context, out io.Writer, root string) error {
	result := gatherOnboarding(ctx, root)
	renderOnboarding(out, result)
	return nil
}

func gatherOnboarding(ctx context.Context, root string) onboardingResult {
	r := onboardingResult{HarnessV: version.Version}
	for _, t := range onboardingTools {
		r.Tools = append(r.Tools, probeTool(ctx, t))
	}
	for _, t := range onboardingAdapters {
		r.Adapters = append(r.Adapters, probeTool(ctx, t))
	}
	r.Suggested = pickSuggestedAdapter(r.Adapters, root)
	return r
}

func probeTool(ctx context.Context, t toolCheck) checkedTool {
	c := checkedTool{toolCheck: t}
	path, err := exec.LookPath(t.binary)
	if err != nil || path == "" {
		return c
	}
	c.found = true
	if v := probeVersion(ctx, t.binary); v != "" {
		c.version = v
	}
	return c
}

func probeVersion(ctx context.Context, binary string) string {
	cmd := exec.CommandContext(ctx, binary, "--version")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return ""
	}
	line := string(out)
	if idx := indexNL(line); idx > 0 {
		line = line[:idx]
	}
	return trimToWidth(line, 60)
}

func indexNL(s string) int {
	for i, r := range s {
		if r == '\n' || r == '\r' {
			return i
		}
	}
	return -1
}

func trimToWidth(s string, w int) string {
	if len(s) <= w {
		return s
	}
	return s[:w] + "…"
}

func pickSuggestedAdapter(adapters []checkedTool, root string) string {
	reg, _, err := agentcmd.LoadAll(root)
	if err == nil {
		ids := reg.IDs()
		for _, preferred := range []string{"ollama", "kimi", "antigravity", "codex", "claude"} {
			for _, id := range ids {
				if id == preferred {
					for _, a := range adapters {
						if a.name == preferred && a.found {
							return preferred
						}
					}
				}
			}
		}
	}
	for _, a := range adapters {
		if a.found {
			return a.name
		}
	}
	return ""
}

func renderOnboarding(out io.Writer, r onboardingResult) {
	fmt.Fprintln(out, ui.Heading.Render("harness onboarding"))
	fmt.Fprintf(out, "  %s harness   %s\n", ui.Muted.Render("·"), ui.Accent.Render(r.HarnessV))

	fmt.Fprintln(out, "\n"+ui.Heading.Render("system tools"))
	for _, t := range r.Tools {
		renderTool(out, t)
	}

	fmt.Fprintln(out, "\n"+ui.Heading.Render("agent adapters"))
	for _, t := range r.Adapters {
		renderTool(out, t)
	}

	fmt.Fprintln(out, "\n"+ui.Heading.Render("next steps"))
	if r.Suggested != "" {
		fmt.Fprintf(out, "  1. pin an agent:   %s\n", ui.Accent.Render("harness use "+r.Suggested))
	} else {
		fmt.Fprintf(out, "  1. %s no agent CLI on PATH — install one above to enable chat\n", ui.MarkWarn())
	}
	fmt.Fprintf(out, "  2. scaffold:        %s\n", ui.Accent.Render("harness new python-ecommerce ./my-api --yes --with-deps"))
	fmt.Fprintf(out, "  3. open chat:       %s\n", ui.Accent.Render("cd my-api && harness chat --auto-gate"))
	fmt.Fprintf(out, "  4. drive a feature: %s\n", ui.Muted.Render(`/drive add /healthz with pytest`))
	fmt.Fprintf(out, "  5. tutorial:        %s\n", ui.Muted.Render("docs/TUTORIAL-TODOIST.md"))
}

func renderTool(out io.Writer, c checkedTool) {
	mark := ui.MarkFail()
	if c.found {
		mark = ui.MarkSuccess()
	}
	line := fmt.Sprintf("  %s %-10s", mark, c.name)
	if c.found {
		line += "  " + ui.Muted.Render(c.version)
	} else {
		line += "  " + ui.Muted.Render(c.purpose+" — install: "+c.installHint)
	}
	fmt.Fprintln(out, line)
}
