// SPDX-License-Identifier: MIT

package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	mcppkg "github.com/ropeixoto/harnessx/internal/mcppkg"
	"github.com/ropeixoto/harnessx/internal/ui"
)

func installedAdapterIDs(adapters []checkedTool) []string {
	out := make([]string, 0, len(adapters))
	for _, a := range adapters {
		if a.found {
			out = append(out, a.name)
		}
	}
	return out
}

func offerMultiAdapterRoutes(in *bufio.Reader, out io.Writer, root string, adapters []checkedTool) {
	installed := installedAdapterIDs(adapters)
	if len(installed) < 2 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("multi-adapter routing"))
	fmt.Fprintln(out, "  map task tags (planning / implementation / cheap_review) to different adapters")
	fmt.Fprintln(out, "  so /plan hits a cheap model and plain text hits a stronger one.")
	if !askYesNo(in, out, "configure routes now?", true) {
		fmt.Fprintln(out, "  skipped — edit .harness/config/routes.yaml later")
		return
	}
	tasks := []string{"planning", "implementation", "cheap_review"}
	picks := map[string]string{}
	for _, tag := range tasks {
		idx, err := askChoice(in, out, "  "+ui.Accent.Render(tag)+" — pick adapter:", installed, 0)
		if err != nil {
			return
		}
		picks[tag] = installed[idx]
	}
	dir := filepath.Join(root, ".harness", "config")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintf(out, "  %s mkdir: %v\n", ui.MarkFail(), err)
		return
	}
	body := renderRoutesYAML(picks, installed)
	path := filepath.Join(dir, "routes.yaml")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fmt.Fprintf(out, "  %s write %s: %v\n", ui.MarkFail(), path, err)
		return
	}
	fmt.Fprintf(out, "  %s wrote %s\n", ui.MarkSuccess(), ui.Accent.Render(path))
}

func renderRoutesYAML(picks map[string]string, installed []string) string {
	tasks := []string{"planning", "implementation", "cheap_review"}
	var b strings.Builder
	b.WriteString("# generated by `harness onboarding --interactive`\n")
	b.WriteString("routes:\n")
	for _, tag := range tasks {
		primary, ok := picks[tag]
		if !ok {
			continue
		}
		b.WriteString("  " + tag + ":\n")
		b.WriteString("    primary: " + primary + "\n")
		fallback := []string{}
		for _, id := range installed {
			if id != primary {
				fallback = append(fallback, id)
			}
		}
		if len(fallback) > 0 {
			b.WriteString("    fallback: [" + strings.Join(fallback, ", ") + "]\n")
		}
	}
	return b.String()
}

func offerBackupQuickstart(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	if _, err := exec.LookPath("rclone"); err != nil {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("backup quickstart"))
	fmt.Fprintln(out, "  print the 3-step recipe to configure a remote (gdrive / s3 / fs)")
	if !askYesNo(in, out, "show recipe?", false) {
		fmt.Fprintln(out, "  skipped — run `harness backup quickstart` later")
		return
	}
	if err := runHarnessSubcommand(ctx, out, root, "backup", "quickstart"); err != nil {
		fmt.Fprintf(out, "  %s backup quickstart: %v\n", ui.MarkFail(), err)
	}
}

func offerCiInstallMissing(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	if _, err := exec.LookPath("pip"); err != nil {
		if _, err2 := exec.LookPath("pip3"); err2 != nil {
			return
		}
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("python sensor tools"))
	fmt.Fprintln(out, "  pip-install optional bandit / mypy / pip-audit so `harness ci` runs the full sensor catalogue")
	if !askYesNo(in, out, "install now?", false) {
		fmt.Fprintln(out, "  skipped — run `harness ci --install-missing` later")
		return
	}
	if err := runHarnessSubcommand(ctx, out, root, "ci", "--install-missing"); err != nil {
		fmt.Fprintf(out, "  %s ci --install-missing: %v\n", ui.MarkFail(), err)
	}
}

func offerMissingToolInstalls(ctx context.Context, in *bufio.Reader, out io.Writer, tools []checkedTool) {
	missing := []checkedTool{}
	for _, t := range tools {
		if !t.found && strings.HasPrefix(t.installHint, "brew install ") {
			missing = append(missing, t)
		}
	}
	if len(missing) == 0 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("missing system tools"))
	for _, t := range missing {
		fmt.Fprintf(out, "  %s missing — install via %s ?\n", ui.Accent.Render(t.name), ui.Muted.Render(t.installHint))
		if !askYesNo(in, out, "  install now?", true) {
			fmt.Fprintln(out, "  skipped "+t.name)
			continue
		}
		args := strings.Fields(strings.TrimPrefix(t.installHint, "brew install "))
		bargs := append([]string{"install"}, args...)
		fmt.Fprintln(out, "  → brew "+strings.Join(bargs, " "))
		c := exec.CommandContext(ctx, "brew", bargs...)
		c.Stdout = out
		c.Stderr = out
		if err := c.Run(); err != nil {
			fmt.Fprintf(out, "  %s brew install %s failed: %v\n", ui.MarkFail(), t.name, err)
			continue
		}
		fmt.Fprintln(out, "  "+ui.MarkSuccess()+" installed "+t.name)
	}
}

func offerAdapterPin(ctx context.Context, in *bufio.Reader, out io.Writer, root string, adapters []checkedTool) error {
	installed := []string{}
	for _, a := range adapters {
		if a.found {
			installed = append(installed, a.name)
		}
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("adapter pin"))
	if len(installed) == 0 {
		fmt.Fprintln(out, "  "+ui.MarkWarn()+" no agent CLI on PATH; install one of: claude / codex / gemini / kimi / ollama")
		return nil
	}
	choice, err := askChoice(in, out, "  pick the default adapter:", append(installed, "skip"), 0)
	if err != nil {
		return err
	}
	if choice == len(installed) {
		fmt.Fprintln(out, "  skipped pin — use `harness use <id>` later")
		return nil
	}
	pick := installed[choice]
	if err := runHarnessSubcommand(ctx, out, root, "use", pick); err != nil {
		return fmt.Errorf("onboarding: pin %s: %w", pick, err)
	}
	fmt.Fprintln(out, "  "+ui.MarkSuccess()+" pinned "+ui.Accent.Render(pick))
	return nil
}

func offerScaffold(ctx context.Context, in *bufio.Reader, out io.Writer) {
	fmt.Fprintln(out, "\n"+ui.Heading.Render("scaffold a starter project?"))
	stacks := []string{
		"python-ecommerce (FastAPI todo skeleton)",
		"rails (Rails 7 API skeleton)",
		"go (net/http server)",
		"rust (Axum web server)",
		"ruby (Sinatra app)",
		"react (Vite + Vitest)",
		"skip",
	}
	idx, err := askChoice(in, out, "  pick a stack:", stacks, len(stacks)-1)
	if err != nil {
		return
	}
	if idx == len(stacks)-1 {
		fmt.Fprintln(out, "  skipped scaffold — run `harness new <stack> ./dir --yes --with-deps` later")
		return
	}
	stackID := strings.Fields(stacks[idx])[0]
	target, ok := askLine(in, out, "  target directory", "./my-"+stackID)
	if !ok {
		return
	}
	withDeps := askYesNo(in, out, "  install dependencies (--with-deps)?", true)
	args := []string{"new", stackID, target, "--yes"}
	if withDeps {
		args = append(args, "--with-deps")
	}
	if err := runHarnessSubcommand(ctx, out, ".", args...); err != nil {
		fmt.Fprintf(out, "  %s scaffold failed: %v\n", ui.MarkFail(), err)
		return
	}
	fmt.Fprintf(out, "  %s scaffold ready at %s\n", ui.MarkSuccess(), ui.Accent.Render(target))
	fmt.Fprintf(out, "  next: %s\n", ui.Muted.Render("cd "+target+" && harness chat --auto-gate"))
}

func offerMCPSetup(ctx context.Context, in *bufio.Reader, out io.Writer, root string) {
	names, err := mcppkg.List()
	if err != nil || len(names) == 0 {
		return
	}
	fmt.Fprintln(out, "\n"+ui.Heading.Render("MCP servers"))
	fmt.Fprintf(out, "  bundled templates: %s\n", strings.Join(names, ", "))
	fmt.Fprintln(out, "  external search:   harness mcp search <term>  (modelcontextprotocol registry)")
	choice, err := askChoice(in, out, "  setup:", []string{
		"install all defaults (recommended)",
		"search bundled by substring (then pick a few)",
		"skip — configure later",
	}, 0)
	if err != nil {
		return
	}
	switch choice {
	case 0:
		for _, name := range names {
			if err := runHarnessSubcommand(ctx, out, root, "mcp", "install", name, "--yes"); err != nil {
				fmt.Fprintf(out, "  %s install %s: %v\n", ui.MarkFail(), name, err)
				continue
			}
			fmt.Fprintf(out, "  %s installed %s\n", ui.MarkSuccess(), ui.Accent.Render(name))
		}
	case 1:
		offerMCPSubstringPick(ctx, in, out, root, names)
	default:
		fmt.Fprintln(out, "  skipped — run `harness mcp install <name>` later")
	}
}

func offerMCPSubstringPick(ctx context.Context, in *bufio.Reader, out io.Writer, root string, names []string) {
	for {
		fmt.Fprint(out, "  filter (substring, empty to list all, 'done' to finish): ")
		line, _ := in.ReadString('\n')
		q := strings.TrimSpace(line)
		if q == "done" {
			return
		}
		filtered := []string{}
		for _, n := range names {
			if q == "" || strings.Contains(n, q) {
				filtered = append(filtered, n)
			}
		}
		if len(filtered) == 0 {
			fmt.Fprintf(out, "  %s no matches for %q\n", ui.MarkWarn(), q)
			continue
		}
		filtered = append(filtered, "done")
		idx, err := askChoice(in, out, "  pick:", filtered, len(filtered)-1)
		if err != nil || idx == len(filtered)-1 {
			return
		}
		name := filtered[idx]
		if err := runHarnessSubcommand(ctx, out, root, "mcp", "install", name, "--yes"); err != nil {
			fmt.Fprintf(out, "  %s install %s: %v\n", ui.MarkFail(), name, err)
			continue
		}
		fmt.Fprintf(out, "  %s installed %s\n", ui.MarkSuccess(), ui.Accent.Render(name))
	}
}
