package sensors

import (
	"bufio"
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/ropeixoto/harnessx/internal/index"
	"gopkg.in/yaml.v3"
)

type CommentStyleSensor struct {
	IDValue string
	Config  CommentStyleConfig
}

type CommentStyleConfig struct {
	BannedPatterns []string `yaml:"banned_patterns"`
	RequireTODORef bool     `yaml:"require_todo_ref"`
	MaxRunLines    int      `yaml:"max_consecutive_comment_lines"`
	ForbidWhat     bool     `yaml:"forbid_what_comments"`
	Disabled       bool     `yaml:"disabled"`
}

func defaultCommentStyleConfig() CommentStyleConfig {
	return CommentStyleConfig{
		RequireTODORef: true,
		MaxRunLines:    8,
		ForbidWhat:     true,
		BannedPatterns: []string{
			`^//\s*do not (modify|edit|change)`,
			`^//\s*generated by`,
		},
	}
}

func (s CommentStyleSensor) ID() string                     { return s.IDValue }
func (s CommentStyleSensor) Category() Category             { return CatLint }
func (s CommentStyleSensor) Kind() Kind                     { return KindComputational }
func (s CommentStyleSensor) AppliesTo(_ index.Profile) bool { return true }

var todoRefRE = regexp.MustCompile(`TODO\b.*[A-Z]+-\d+|TODO\b.*#\d+|TODO\b.*\(@?\w+\)`)
var whatCommentRE = regexp.MustCompile(`(?i)^//\s*(set|get|return|increment|decrement|init|initialize|update|add|remove|check|loop|iterate)\b`)

func (s CommentStyleSensor) Run(rc RunCtx) Result {
	start := time.Now()
	res := Result{ID: s.IDValue, Category: s.Category(), Kind: s.Kind()}
	cfg := s.loadConfig(rc.Root)
	if cfg.Disabled {
		res.Status = StatusSkipped
		res.Detail = "comment_style disabled via .harness/config/comment_style.yaml"
		res.Duration = time.Since(start)
		return res
	}
	walkCtx, cancel := context.WithTimeout(rc.Ctx, 60*time.Second)
	defer cancel()
	var findings []SmellFinding
	bannedREs := compileAll(cfg.BannedPatterns)
	exts := map[string]bool{}
	for _, e := range []string{".go", ".py", ".ts", ".tsx", ".js", ".jsx", ".rb", ".rs", ".java", ".kt", ".swift", ".ex", ".exs", ".php", ".cs", ".dart"} {
		exts[e] = true
	}
	_ = filepath.WalkDir(rc.Root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if walkCtx.Err() != nil {
			return walkCtx.Err()
		}
		if d.IsDir() {
			if isSkippedDir(d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if !exts[strings.ToLower(filepath.Ext(path))] {
			return nil
		}
		findings = append(findings, s.scanComments(path, rc.Root, cfg, bannedREs)...)
		return nil
	})
	res.Duration = time.Since(start)
	if len(findings) == 0 {
		res.Status = StatusPassed
		res.Detail = "no comment-style issues"
		return res
	}
	res.Status = StatusFailed
	res.Detail = fmt.Sprintf("%d comment issue(s)", len(findings))
	if rc.OutputDir != "" {
		_ = os.MkdirAll(rc.OutputDir, 0o755)
		p := filepath.Join(rc.OutputDir, s.IDValue+".log")
		_ = os.WriteFile(p, []byte(renderFindings(findings)), 0o644)
		res.OutputPath = p
	}
	return res
}

func (s CommentStyleSensor) loadConfig(root string) CommentStyleConfig {
	cfg := s.Config
	if cfg.MaxRunLines == 0 && !cfg.RequireTODORef && !cfg.ForbidWhat && len(cfg.BannedPatterns) == 0 {
		cfg = defaultCommentStyleConfig()
	}
	override := filepath.Join(root, ".harness", "config", "comment_style.yaml")
	if data, err := os.ReadFile(override); err == nil {
		var raw CommentStyleConfig
		if err := yaml.Unmarshal(data, &raw); err == nil {
			if raw.MaxRunLines > 0 {
				cfg.MaxRunLines = raw.MaxRunLines
			}
			cfg.RequireTODORef = raw.RequireTODORef
			cfg.ForbidWhat = raw.ForbidWhat
			cfg.Disabled = raw.Disabled
			if len(raw.BannedPatterns) > 0 {
				cfg.BannedPatterns = raw.BannedPatterns
			}
		}
	}
	return cfg
}

func compileAll(patterns []string) []*regexp.Regexp {
	var out []*regexp.Regexp
	for _, p := range patterns {
		re, err := regexp.Compile(p)
		if err != nil {
			continue
		}
		out = append(out, re)
	}
	return out
}

func (s CommentStyleSensor) scanComments(path, root string, cfg CommentStyleConfig, banned []*regexp.Regexp) []SmellFinding {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()
	rel, _ := filepath.Rel(root, path)
	var findings []SmellFinding
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 2*1024*1024)
	lineNo := 0
	consecutiveStart := 0
	runLen := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		trim := strings.TrimSpace(line)
		if !isComment(trim) {
			if cfg.MaxRunLines > 0 && runLen > cfg.MaxRunLines {
				findings = append(findings, SmellFinding{
					Path: rel, Line: consecutiveStart, Kind: "comment_block_long",
					Msg: fmt.Sprintf("%d-line comment block (limit %d)", runLen, cfg.MaxRunLines),
				})
			}
			runLen = 0
			continue
		}
		if runLen == 0 {
			consecutiveStart = lineNo
		}
		runLen++
		for _, re := range banned {
			if re.MatchString(trim) {
				findings = append(findings, SmellFinding{
					Path: rel, Line: lineNo, Kind: "banned_comment",
					Msg: fmt.Sprintf("matches banned pattern %s", re.String()),
				})
			}
		}
		if cfg.RequireTODORef && strings.Contains(trim, "TODO") && !todoRefRE.MatchString(trim) {
			findings = append(findings, SmellFinding{
				Path: rel, Line: lineNo, Kind: "todo_without_ref",
				Msg: "TODO without ticket / issue reference (FOO-123, #42, or (@owner))",
			})
		}
		if cfg.ForbidWhat && whatCommentRE.MatchString(trim) {
			findings = append(findings, SmellFinding{
				Path: rel, Line: lineNo, Kind: "what_comment",
				Msg: "comment restates what the code does; prefer naming or explain why",
			})
		}
	}
	if cfg.MaxRunLines > 0 && runLen > cfg.MaxRunLines {
		findings = append(findings, SmellFinding{
			Path: rel, Line: consecutiveStart, Kind: "comment_block_long",
			Msg: fmt.Sprintf("%d-line comment block (limit %d)", runLen, cfg.MaxRunLines),
		})
	}
	return findings
}

func isComment(trim string) bool {
	if strings.HasPrefix(trim, "//") {
		return true
	}
	if strings.HasPrefix(trim, "#") && !strings.HasPrefix(trim, "#!") {
		return true
	}
	if strings.HasPrefix(trim, "--") {
		return true
	}
	if strings.HasPrefix(trim, "*") || strings.HasPrefix(trim, "/*") {
		return true
	}
	return false
}
